services:
  - type: web
    name: drishti-platform
    env: python
    rootDirectory: DrishtiPlatform
    buildCommand: "./build.sh"
    startCommand: "gunicorn DrishtiPlatform.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: drishti-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: drishti-db
    databaseName: drishti
    user: drishti_user
    plan: free
