databases:
  - name: drishti_db
    databaseName: drishti_db
    user: drishti_user
    plan: free

services:
  - type: web
    name: drishti-platform
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn DrishtiPlatform.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: drishti_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
