services:
  - type: web
    name: DrishtiPlatform
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn DrishtiPlatform.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: drishti-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: drishti-db
    databaseName: drishti
    user: drishti_user
    plan: free # or starter, depending on needs
